### ISSUE TITLE
Module not found: Error: Can't resolve './styles/theme' in '/root/shopify-monitor/client'

### ISSUE THREAD

**Issue by simonschwitzky** [alii/monitor#23]
Hi, trying to run your project I get this error:
`Module not found: Error: Can't resolve './styles/theme' in '/root/shopify-monitor/client'`.
Also, it seems like @babel/preset-env needs a bump to properly work..
Also, if I manually change the import to `theme.scss`, I can get all to build but I all I see after yarn start is a blank, white page.
Is this still under development? Thanks!

**Comment by alii** [comment]
It is still under development. Please be patient as we haven't announced this project as complete yet.
